### ISSUE TITLE
ts-transformer-imports not working with ttypescript and ts-node (tsconfig-paths & ts-transform-paths work ok)

### ISSUE THREAD

**Issue by opensas** [grrowl/ts-transformer-imports#17]
Check the following issue I filed at ttypescript: https://github.com/cevek/ttypescript/issues/71

When using ts-node with `npx ts-node -r tsconfig-paths/register src/start.ts` it works ok

when using `npx ts-node -C ttypescript src/start.ts` it throws the following error:

```
> ts-node -C ttypescript src/start.ts

C:\data\devel\apps\sgte-it\coordinacion\juridicos\wspjn\src\app.ts:1
import express from 'express'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:881:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
```

When I updated the project and used @zerollup/ts-transform-paths instead of ts-transformer-imports it worked ok (BTW, have you considered joining forces??? it looks like both projects do the same)

Fully reproducible example: https://gitlab.com/opensas/tts-node_test

More info: https://github.com/cevek/ttypescript/issues/71

**Comment by grrowl** [comment]
@opensas you're right, `@zerollup/ts-transform-paths` looks really good! Honestly I wish I had time to bring this up to feature parity with his, unfortunately this module isn't in use at my current day job.

If [`@zerollup/ts-transform-paths`](https://github.com/zerkalica/zerollup/tree/master/packages/ts-transform-paths) handles all features that `ts-transform-imports` does I'll depreciate this module and point to theirs in this readme instead.
