### ISSUE TITLE
Plugin does not work

### ISSUE THREAD

**Issue by athlan** [grrowl/ts-transformer-imports#3]
After performing:

```
npm install --save-dev ttypescript
npm install --save-dev ts-transformer-imports
tsc
```

and added to `tsconfig.json`:
```
    "compilerOptions": {
        ...

        "baseUrl": "src/ts",
        "paths": {
            "My/Import/*": ["Test/*"]
        },
        "plugins": [
            { "transform": "ts-transformer-imports" }
        ]
    },
```

Output of .js files is still relative path:

```
const MyImport_1 = require("My/Import");
```

Of course it results:
```
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'My/Import//SomeDep'
```

tsc version:
Version 3.2.2

Imported versions:
```
    "ts-transformer-imports": "^0.3.0",
    "tsc": "1.20150623.0",
    "ttypescript": "^1.5.5",
```

Build command usage:
```
tsc
```

**Comment by grrowl** [comment]
I feel you. We've only tested with `baseDir` and would love to (but have barely any free time) write more comprehensive tests— for the time being it might be worth looking at a similar project like https://github.com/dropbox/ts-transform-import-path-rewrite

**Comment by danielpza** [comment]
Shouldn't it be `ttsc` the command used ?

**Comment by grrowl** [comment]
Hi @athlan, I added a unit test to assert your use case and it looks the behaviour works. If you still experience the problem please let me know so we can fix :)
