### ISSUE TITLE
Transformer is not working on windows system

### ISSUE THREAD

**Issue by the-noob-101** [grrowl/ts-transformer-imports#7]
## Actual behavior :

When running on a windows system, the transformation are not the same than in a unix system.

### Steps to reproduce

Use the package on a windows system

### Investigation 

```
const transformerFactory: ts.TransformerFactory<ts.SourceFile> = context => {
  const compilerOptions = context.getCompilerOptions()
  console.log(compilerOptions.baseUrl);
  const absoluteBaseUrl = compilerOptions.baseUrl && compilerOptions.baseUrl[0] === '/' ? compilerOptions.baseUrl : nodePath.join(process.cwd(), compilerOptions.baseUrl || '.');
  const matchPathFunc = createMatchPath(absoluteBaseUrl, compilerOptions.paths || {});

  return file => visitSourceFile(file, context, matchPathFunc) as ts.SourceFile;
};
```

When logging baseUrl here, I noticed that it was equal to "C:/your/path/to/project". 'C' can of course be any letter, it just represents the hard disk. 

Thus, the transformerFactory was joining baseUrl and process.cwd(), resulting in a path like this : 
 `"C:/your/path/to/project/C:/your/path/to/project/"`
which, obviously, didn't exist. 
It is leading to not making any transformation in the end because the transformer is not able to resolve the actual path of the file.

## Desired behavior

We should be able to use this package on a windows system

## Related PR

Coming soon

**Comment by grrowl** [comment]
Fixed by #8
